#!/bin/sh

# INIT-DAEMONS
xrdb ~/.Xresources
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
xsetroot -cursor_name left_ptr &
sxhkd &
killall picom; picom &
vmware-user-suid-wrapper &
xss-lock blurlock &

# Applications
dunst &
imwheel &
nm-applet &
pamac-tray &
~/.config/conky/start-conky.sh &
