#!/bin/sh
# Applications
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
xrdb ~/.Xresources
pgrep conky || ~/.config/conky/start-conky.sh &
vmware-user-suid-wrapper &
imwheel &
nm-applet &
pamac-tray &
